version: '3.8'

services:
  portfolio:
    image: us-docker.pkg.dev/pet-pocket-5300/varun-portfolio/varun-portfolio:latest
    container_name: varun-portfolio
    ports:
      - "80:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/var/log/nginx 